LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)

CONSOLE_OUTPUT_TO_PLATFORM_PUTC ?= 1

MODULE_DEPS := \
	lib/cbuf

MODULE_DEFINES += \
	CONSOLE_OUTPUT_TO_PLATFORM_PUTC=$(CONSOLE_OUTPUT_TO_PLATFORM_PUTC)

MODULE_SRCS += \
   $(LOCAL_DIR)/console.c \
   $(LOCAL_DIR)/io.c \

include make/module.mk
