/*
 * Copyright (c) 2015 Brian Swetland
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

DEFIRQ(DAC)
DEFIRQ(M0APP)
DEFIRQ(DMA)
DEFIRQ(RESERVED03)
DEFIRQ(FLASHEEPROM)
DEFIRQ(ETHERNET)
DEFIRQ(SDIO)
DEFIRQ(LCD)
DEFIRQ(USB0)
DEFIRQ(USB1)
DEFIRQ(SCT)
DEFIRQ(RITIMER)
DEFIRQ(TIMER0)
DEFIRQ(TIMER1)
DEFIRQ(TIMER2)
DEFIRQ(TIMER3)
DEFIRQ(MCPWM)
DEFIRQ(ADC0)
DEFIRQ(I2C0)
DEFIRQ(I2C1)
DEFIRQ(SPI_INT)
DEFIRQ(ADC1)
DEFIRQ(SSP0)
DEFIRQ(SSP1)
DEFIRQ(USART0)
DEFIRQ(UART1)
DEFIRQ(USART2)
DEFIRQ(USART3)
DEFIRQ(I2S0)
DEFIRQ(I2S1)
DEFIRQ(SPIFI)
DEFIRQ(SGPIO_INT)
DEFIRQ(PIN_INT0)
DEFIRQ(PIN_INT1)
DEFIRQ(PIN_INT2)
DEFIRQ(PIN_INT3)
DEFIRQ(PIN_INT4)
DEFIRQ(PIN_INT5)
DEFIRQ(PIN_INT6)
DEFIRQ(PIN_INT7)
DEFIRQ(GINT0)
DEFIRQ(GINT1)
DEFIRQ(EVENTROUTER)
DEFIRQ(C_CAN1)
DEFIRQ(RESERVED44)
DEFIRQ(ADCHS)
DEFIRQ(ATIMER)
DEFIRQ(RTC)
DEFIRQ(RESERVED48)
DEFIRQ(WWDT)
DEFIRQ(M0SUB)
DEFIRQ(C_CAN0)
DEFIRQ(QEI)
