# Building top-level Rust
#
# We build all of the the rust code that is included in lk with a single invocation of make.  Cargo
# does a good job of managing all of the dependencies within Rust (with the main work needed on our
# part are the header files used by bindgen.
#
# In order to allow rust-analyzer to be used naturally, we synthesize the top-level crate that cargo
# builds.  This crate will consist of references to the top-level crates selected to be included in
# the build.

LOCAL_DIR := $(GET_LOCAL_DIR)

# This must match the crate name in the Cargo.toml.
CRATE_NAME := rust_support

MODULE := $(LOCAL_DIR)

MODULE_SRCDIR := $(MODULE)
MODULE_BUILDDIR := $(call TOBUILDDIR,$(MODULE_SRCDIR))

MODULE_SRCS := \
	       $(MODULE_SRCDIR)/Cargo.toml \
	       $(MODULE_SRCDIR)/src/lib.rs
MODULE_OBJS := $(foreach d,$(MODULE_SRCS),$(call TOBUILDDIR,$(d)))

# TODO: Set this by the arch.
RUST_TARGET := aarch64-unknown-none

define TOML_ESC
$(subst \,\\,$(subst ",\",$1))
endef

CARGO_CONFIG := $(MODULE_BUILDDIR)/.cargo/config.toml

# TODO: Allow debug/release builds
MODULE_OBJECT := $(MODULE_BUILDDIR)
MODULE_OBJECT := $(call TOBUILDDIR,$(MODULE_SRCDIR)/target/$(RUST_TARGET)/debug/lib$(CRATE_NAME).a)

$(MODULE_OBJECT).phony:
.PHONY: $(MODULE_OBJECT).phony

$(MODULE_OBJECT): MODULE_BUILDDIR:=$(MODULE_BUILDDIR)

# Override with module local values for the build rule.
$(MODULE_OBJECT): $(MODULE_OBJECT).phony $(MODULE_OBJS) $(CARGO_CONFIG)
	cd $(MODULE_BUILDDIR); \
		cargo build

EXTRA_OBJS := $(EXTRA_OBJS) $(MODULE_OBJECT)

# Bring in the source files via copy.
# TODO: Symlinks would be better because then it wouldn't be an issue if the user edits these.
$(MODULE_BUILDDIR)/%: $(MODULE_SRCDIR)/%.in
	mkdir -p $(dir $@)
	cp -p $< $@
$(MODULE_BUILDDIR)/src/%: $(MODULE_SRCDIR)/src/%.in
	mkdir -p $(dir $@)
	cp -p $< $@

$(CARGO_CONFIG).phony:
.PHONY: $(CARGO_CONFIG).phony

$(CARGO_CONFIG): MODULE_SRCDIR:=$(MODULE_SRCDIR)

$(CARGO_CONFIG): $(CARGO_CONFIG).phony
	mkdir -p $(dir $@)
	@tmp="$@.tmp"; { \
		echo "# AUTOGENERATED -- edit $(MODULE_SRCDIR)/rules.mk instead"; \
		echo "[build]"; \
		echo 'target = "$(RUST_TARGET)"'; \
		echo; \
		echo "[env]"; \
		echo 'GLOBAL_INCLUDES = { value = "$(call TOML_ESC,$(GLOBAL_INCLUDES))", force = true }'; \
	} > "$$tmp"; \
	cmp -s "$$tmp" "$@" || mv "$$tmp" "$@"; \
	rm -f "$$tmp"

MODULE :=
MODULE_SRCDIR :=
MODULE_BUILDDIR :=
MODULE_OBJECT :=
MODULE_SRCS :=
MODULE_OBJS :=

CARGO_CONFIG :=
