#pragma  once

#define MIO_TRI_ENABLE                 (1)
#define MIO_L0_SEL                     (1 << 1)
#define MIO_L1_SEL                     (1 << 2)
#define MIO_L2_SEL(x)                  (x << 3)
#define MIO_L3_SEL(x)                  (x << 5)
#define MIO_SPEED_FAST                 (1 << 8)
#define MIO_IO_TYPE(x)                 (x << 9)
#define MIO_IO_TYPE_LVCMOS18           MIO_IO_TYPE(0x1)
#define MIO_IO_TYPE_LVCMOS25           MIO_IO_TYPE(0x2)
#define MIO_IO_TYPE_LVCMOS33           MIO_IO_TYPE(0x3)
#define MIO_IO_TYPE_HSTL               MIO_IO_TYPE(0x4)
#define MIO_PULLUP                     (1 << 12)
#define MIO_DISABLE_RCVR               (1 << 13)
