# Rust support for LK, main package

[package]
name = "lk"
version = "0.1.0"
edition = "2024"
description = """
Rust interface to LK
"""
license = "MIT"

[dependencies.lk-sys]
version = "0.1.0"
path = "../../rust/lk-sys"

[dependencies.log]
version = "0.4.27"
