#!/bin/sh

# build everything in the projects directory
PROJECTS=`echo project/* | xargs basename | sed 's/\.mk//'`
FAILED=""

for p in $PROJECTS; do
	PROJECT=$p nice make -j4 || FAILED="$FAILED $p"
done

if [ "$FAILED" != "" ]; then
	echo
	echo some projects have failed to build:
	echo $FAILED
fi
