#!/bin/sh

make foundation-arm64-test -j4 || exit 1

case `uname` in
    Darwin)
        scp build-foundation-arm64-test/lk.elf vmint:. &&
        ssh vmint Foundation_v8pkg/models/Linux64_GCC-4.1/Foundation_v8 --use-real-time --visualization --image lk.elf
        ssh vmint killall Foundation_v8
        ;;
    Linux)
        Foundation_v8 --use-real-time --visualization --image build-foundation-arm64-test/lk.elf $@
        ;;
esac

