#!/bin/sh

export PROJECT=adk2012-test
UART=ttyUSB0

tagit
make &&
adk2tool /dev/$UART erase &&
bossac -p $UART -b -w build-$PROJECT/lk.bin &&
adk2tool /dev/$UART reset &&
adk2tool /dev/$UART console
