#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"$DIR"/make-parallel or1ksim

qemu-system-or1k -nographic -M or1k-sim -cpu any \
    -kernel build-or1ksim/lk.elf $@

#or1k-elf-sim -f platform/or1ksim/or1ksim.cfg build-or1ksim/lk.elf $@
