#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set -e
set -x

$DIR/make-parallel qemu-microblaze-test
qemu-system-microblaze -kernel build-qemu-microblaze-test/lk.elf -nographic $@
