#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/qemu-shared.sh"

function HELP {
    echo "help:"
    echo "-c <cpu>          : CPU type (default: 68040, valid: 68000, 68010, 68020, 68030, 68040, 68060)"
    echo "-m <memory in MB> : memory size (default: 64 MB)"
    echo "-p <project>      : specify the project to build (default: qemu-virt-m68k-test)"
    echo
    echo "-A <cmd line>     : append command line (may be used multiple times)"
    echo "-d <disk image>   : add a virtio disk device (may be used multiple times)"
    echo "-n                : add a virtio network device (user mode networking)"
    echo "-N <network driver> : specify network driver (requires -n or -t, e.g., virtio-net-device, virtio-net-pci)"
    echo "-t                : add a virtio tap network device (requires tap interface setup)"
    echo "-g                : add a virtio display (GPU, keyboard, mouse)"
    echo "-f <shared dir>   : add a virtio 9p device with a host shared directory"
    echo
    echo "-X                : print QEMU command and exit (dry run)"
    echo
    echo "-h                : show this help"
    echo "all arguments after -- are passed to qemu directly"
    exit 1
}

CPU=68040
MEMSIZE=64
PROJECT=""
DO_DRYRUN=0
DO_NET=0
DO_NET_TAP=0
DO_DISPLAY=0
DISK_IMAGES=()
CMDLINE=""
DO_V9P=0
DO_V9P_DIR=""
NETDEV="virtio-net-device"
DO_NETDEV_OVERRIDE=0

while getopts A:c:d:f:gm:p:XnhtN FLAG; do
    case $FLAG in
        A) CMDLINE+="${CMDLINE:+ }$(quote_cmdline_arg "$OPTARG")";;
        c) CPU=$OPTARG;;
        d) DISK_IMAGES+=("$OPTARG");;
        f) DO_V9P=1; DO_V9P_DIR=$OPTARG;;
        m) MEMSIZE=$OPTARG;;
        n) DO_NET=1;;
        t) DO_NET_TAP=1;;
        N) NETDEV=$OPTARG; DO_NETDEV_OVERRIDE=1;;
        p) PROJECT=$OPTARG;;
        g) DO_DISPLAY=1;;
        X) DO_DRYRUN=1;;
        h) HELP;;
        \?)
            echo "unrecognized option"
            HELP
    esac
done

shift $((OPTIND-1))

if (( DO_NET && DO_NET_TAP )); then
    echo "Error: Cannot use both -n (user network) and -t (tap network) together"
    exit 1
fi

if (( DO_NETDEV_OVERRIDE && ! ( DO_NET || DO_NET_TAP ) )); then
    echo "Error: -N requires either -n (user network) or -t (tap network)"
    exit 1
fi

# validate CPU type
case "$CPU" in
    68000|68010|68020|68030|68040|68060) ;;
    *)
        echo "Error: invalid CPU type '$CPU'. Valid: 68000, 68010, 68020, 68030, 68040, 68060"
        exit 1
        ;;
esac

# allow overriding the project from the environment
if [ -z "$PROJECT" ]; then
    PROJECT="qemu-virt-m68k-test"
fi

export M68K_CPU=${CPU}

# construct a list of args based on previous variables using arrays
ARGS=()
ARGS+=("-machine" "virt")
ARGS+=("-m" "$MEMSIZE")
ARGS+=("-cpu" "m${CPU}")
ARGS+=("-kernel" "build-${PROJECT}/lk.elf")

if [[ -n "$CMDLINE" ]]; then
    ARGS+=("-append" "$CMDLINE")
fi

DISK_COUNT=0
for img in "${DISK_IMAGES[@]}"; do
    ARGS+=("-drive" "if=none,file=${img},id=blk${DISK_COUNT},format=raw")
    ARGS+=("-device" "virtio-blk-device,drive=blk${DISK_COUNT}")
    ((DISK_COUNT++))
done

if (( DO_NET )); then
    ARGS+=("-netdev" "user,id=vmnic,hostname=qemu")
    ARGS+=("-device" "${NETDEV},netdev=vmnic")
elif (( DO_NET_TAP )); then
    # quick note to enable tap interface
    # IFNAME=qemu0
    # BRIDGE=bridge0
    # sudo ip tuntap add name "${IFNAME}" mode tap user $(whoami)
    # sudo ip link set "${IFNAME}" master "${BRIDGE}"
    # sudo ip link set "${IFNAME}" up
    ARGS+=("-netdev" "tap,id=vmnic,ifname=qemu0,script=no,downscript=no")
    ARGS+=("-device" "${NETDEV},netdev=vmnic")
else
    ARGS+=("-net" "none")
fi

if (( DO_DISPLAY )); then
    ARGS+=("-device" "virtio-gpu-device")
    ARGS+=("-serial" "stdio")
    ARGS+=("-device" "virtio-keyboard-device")
    ARGS+=("-device" "virtio-mouse-device")
else
    ARGS+=("-nographic")
fi

if (( DO_V9P )); then
    ARGS+=("-fsdev" "local,path=$DO_V9P_DIR,security_model=mapped,id=v9p0")
    ARGS+=("-device" "virtio-9p-device,fsdev=v9p0,mount_tag=V9P0")
fi

ARGS+=("-device" "virtio-rng-device")

CMD=(qemu-system-m68k "${ARGS[@]}" "$@")

if (( DO_DRYRUN )); then
    echo "${CMD[@]}"
    exit 0
fi

set -e
echo "${CMD[@]}"
"$DIR"/make-parallel PROJECT="$PROJECT"
exec "${CMD[@]}"
