#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PROJECT=stellaris-launchpad-test

"$DIR"/make-parallel &&
lm4flash -v "${BUILDROOT:-.}/build-$PROJECT${BUILDDIR_SUFFIX:-}/lk.bin"
