#!/usr/bin/env python3
#
# Copyright (c) 2026 Travis Geiselbrecht
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT
#
"""Generate the in kernel symbol table from nm output.

Reads the output of `nm -n --defined-only lk.elf` and writes a C file
holding a sorted table of text symbol addresses and their names, which
lib/symtab links into the kernel and searches at runtime.

Addresses are stored as 32 bit offsets from a base address baked into the
generated file, which keeps the table half the size on 64 bit targets and
leaves it free of relocations.

  nm -n --defined-only lk.elf | gen-symtab.py > symtab_data.c

The --verify mode compares the symbols of two nm dumps and fails if they
differ, which is how the build checks that the second link pass did not
move any of the text the table describes.
"""

import argparse
import sys

# nm type letters for text symbols: global, local and weak. Everything else
# (data, bss, rodata, absolute) is not something a pc can land in.
TEXT_TYPES = frozenset('tTwW')

# Addresses beyond the last symbol are not attributed to it, so an image
# whose text is not followed by any other symbol gets this much slop.
END_SLOP = 0x1000


def is_interesting(type_, name):
    """True if the symbol names a chunk of text worth reporting."""
    if type_ not in TEXT_TYPES:
        return False
    # ARM ($a/$d/$t/$x) and RISC-V ($xrv64i2p0...) mapping symbols share
    # addresses with the real functions and would shadow them.
    if name.startswith('$'):
        return False
    # Assembler local labels.
    if name.startswith('.L'):
        return False
    return True


def parse_nm(stream):
    """Parse nm output into (text_symbols, all_addresses).

    text_symbols is a list of (address, name) sorted by address and
    deduplicated, all_addresses is the set of every defined address seen,
    which is used to find where the text ends.
    """
    by_addr = {}
    all_addrs = set()

    for line in stream:
        parts = line.split(maxsplit=2)
        # Undefined symbols have no address and are skipped, as are any
        # stray lines that are not in "address type name" form.
        if len(parts) != 3:
            continue
        addr_str, type_, name = parts
        try:
            addr = int(addr_str, 16)
        except ValueError:
            continue
        name = name.strip()
        all_addrs.add(addr)

        if not is_interesting(type_, name):
            continue

        # Several symbols can share an address. Prefer a global over a
        # local, then the shortest name, then sort order, so that the
        # choice does not depend on the order nm happened to emit them.
        key = (type_.islower(), len(name), name)
        existing = by_addr.get(addr)
        if existing is None or key < existing[0]:
            by_addr[addr] = (key, name)

    syms = sorted((addr, entry[1]) for addr, entry in by_addr.items())
    return syms, all_addrs


def text_end(syms, all_addrs):
    """Pick the address one past the end of the last function.

    nm without --print-size gives no sizes, so use the next defined symbol
    after the last text symbol, which is where rodata starts in every LK
    linker script.
    """
    last = syms[-1][0]
    above = [a for a in all_addrs if a > last]
    return min(above) if above else last + END_SLOP


def c_string(s):
    """Escape a symbol name for use in a C string literal."""
    return s.replace('\\', '\\\\').replace('"', '\\"')


def emit(out, syms, base, end):
    count = len(syms)

    out.write('/*\n')
    out.write(' * Generated by scripts/gen-symtab.py. Do not edit.\n')
    out.write(' *\n')
    out.write(' * Table of kernel text symbols, searched by lib/symtab.\n')
    out.write(' */\n')
    out.write('#include <stdint.h>\n\n')

    out.write('const uintptr_t lk_symtab_base = (uintptr_t)0x%xU;\n' % base)
    out.write('const uint32_t lk_symtab_count = %u;\n\n' % count)

    # One extra entry holds the end of the last function so that a lookup
    # can reject addresses off the end of text.
    out.write('const uint32_t lk_symtab_addr[%u] = {\n' % (count + 1))
    offsets = [addr - base for addr, _ in syms] + [end - base]
    for i in range(0, len(offsets), 8):
        chunk = offsets[i:i + 8]
        out.write('    ' + ' '.join('0x%08x,' % off for off in chunk) + '\n')
    out.write('};\n\n')

    out.write('const uint32_t lk_symtab_nameoff[%u] = {\n' % count)
    nameoffs = []
    pos = 0
    for _, name in syms:
        nameoffs.append(pos)
        pos += len(name) + 1
    for i in range(0, len(nameoffs), 8):
        chunk = nameoffs[i:i + 8]
        out.write('    ' + ' '.join('0x%08x,' % off for off in chunk) + '\n')
    out.write('};\n\n')

    # Left unsized: every name carries its own terminator, so the literal's
    # implicit one is redundant, but spelling the size out as exactly the
    # bytes needed makes the compiler warn that it has to drop it.
    out.write('const char lk_symtab_names[] =\n')
    for _, name in syms:
        out.write('    "%s\\0"\n' % c_string(name))
    out.write('    ;\n')


def load(path):
    with open(path, 'r') as f:
        return parse_nm(f)[0]


def verify(path_a, path_b):
    a = load(path_a)
    b = load(path_b)
    if a == b:
        return 0

    sys.stderr.write(
        'gen-symtab: text symbols moved between link passes, so the embedded\n'
        'symbol table does not describe the final image.\n'
        '  before: %s (%u symbols)\n'
        '  after:  %s (%u symbols)\n' % (path_a, len(a), path_b, len(b)))

    only_a = set(a) - set(b)
    only_b = set(b) - set(a)
    for addr, name in sorted(only_a)[:10]:
        sys.stderr.write('  -0x%x %s\n' % (addr, name))
    for addr, name in sorted(only_b)[:10]:
        sys.stderr.write('  +0x%x %s\n' % (addr, name))
    if len(only_a) > 10 or len(only_b) > 10:
        sys.stderr.write('  ... %u more differences\n' %
                         (len(only_a) + len(only_b) - 20))
    return 1


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--verify', nargs=2, metavar=('BEFORE', 'AFTER'),
                        help='compare two nm dumps instead of generating a table')
    parser.add_argument('-o', '--output', help='write to this file instead of stdout')
    args = parser.parse_args()

    if args.verify:
        return verify(args.verify[0], args.verify[1])

    syms, all_addrs = parse_nm(sys.stdin)
    if not syms:
        sys.stderr.write('gen-symtab: no text symbols found\n')
        return 1

    base = syms[0][0]
    end = text_end(syms, all_addrs)

    out = open(args.output, 'w') if args.output else sys.stdout
    try:
        emit(out, syms, base, end)
    finally:
        if args.output:
            out.close()
    return 0


if __name__ == '__main__':
    sys.exit(main())
